### ISSUE TITLE
Store some meta informations about Session and list active user sessions

### ISSUE THREAD

**Issue by MateuszKubuszok** [branchtalk-io/backend#7]
* [ ] add metadata to Session model
* [ ] when creating Session store what is known about the creator: IP, operating system, browser, etd
* [ ] list that data to User so that it could remotely sign-out out
